language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=2.8.*

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev


before_install:
  - composer selfupdate

install:
  - cp Tests/Fixtures/app/parameters.yml.travis Tests/Fixtures/app/parameters.yml
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
  - php Tests/Fixtures/app/console doctrine:database:create --env=test
  - php Tests/Fixtures/app/console doctrine:schema:create --env=test

script: phpunit --coverage-text
